### ISSUE TITLE
Does this work on linux ?

### ISSUE THREAD

**Issue by rehxnnq** [b8ff/Microsoft-Account-Generator#1]
im getting this error 

Traceback (most recent call last):
  File "/home/linux/Desktop/Microsoft-Account-Generator/Potato Gen/PotatoGen.py", line 6, in <module>
    from win32api import GetSystemMetrics
ModuleNotFoundError: No module named 'win32api'

**Comment by terminated-star** [comment]
I was able to run it inside of wine. It seems to be reliant on windows for some reason.

**Comment by b8ff** [comment]
yeah it was made in windows and should work only on windows

**Comment by TheBlackCookie** [comment]
> im getting this error 
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/linux/Desktop/Microsoft-Account-Generator/Potato Gen/PotatoGen.py", line 6, in <module>
> 
>     from win32api import GetSystemMetrics
> 
> ModuleNotFoundError: No module named 'win32api'
> 
> 

Run pip install win32 inside of terminal
